### ISSUE TITLE
Invalid configuration elements `emitConfigChangeEvents`

### ISSUE THREAD

**Issue by smerle33** [jenkinsci/datadog-plugin#372]
**Describe the bug**
We had an error with the upgrade from 5.5.1 to 5.6.0 : `Invalid configuration elements for type class org.datadog.jenkins.plugins.datadog.DatadogGlobalConfiguration : emitConfigChangeEvents.`

This property has been removed but doesn't seem to be documented

Label the issue properly.
- Add `bug/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
1. within the JCASC configuration under `datadogGlobalConfiguration`
2. use: `emitConfigChangeEvents`

**Expected behavior**
at least information on how to replace this property and a warning of breaking change

**Comment by sarah-witt** [comment]
Hi @smerle thank you for reporting! Our apologies about the removal of the parameter- we will note this on the recent changelog and release a fix to not break JCASC setups. The config change events have not been sent by the plugin for a while, so for now, unsetting `emitConfigChangeEvents` should not have an effect on your plugin’s behavior and should resolve the error. We will push a fix that ensures that the option is deprecated rather than removed so it does not break other configurations.

**Comment by sarah-witt** [comment]
Hi @smerle33 we've released version [5.6.1](https://github.com/jenkinsci/datadog-plugin/blob/master/CHANGELOG.md#561--2023-11-16) of the plugin which should resolve this issue. Please let me know if everything looks good on your side!

**Comment by smerle33** [comment]
we have changed the configuration accordingly with 5.6.0, so we cannot confirm that the 5.6.1 takes care of the parameter declaration, but thanks for the work done !
