### ISSUE TITLE
Datadog errors under 'manage old data' - for pipelines not utilising the plugin

### ISSUE THREAD

**Issue by marmccor** [jenkinsci/datadog-plugin#50]
**Describe the bug**
Errors appearing under 'Manage old Data', which look related to the datadog plugin for Jenkins. 

Label the issue properly.
I've configured the datadog plugin for Jenkins, and setup a valid API token. I haven't begun utilising the plugin yet in any pipelines. 

I noticed Jenkins had flagged some issues with pipelines under 'Manage old Data'. When I click in here, I see a lot of pipelines listed with the below error:
```
MissingFieldException: No field 'emitOnCheckout' found in class 'org.datadog.jenkins.plugins.datadog.DatadogJobProperty'
```

I'm not sure if this is a regression, but I did a bit of searching and couldn't find a direct link to existing issues, nor identify the root cause. 

I did also perform a search for 'emitOnCheckout' in this git repository, but couldn't find any references. that said, when I search for that online in the context of Jenkins, examples are returned which reference the datadog plugin. 

Will also attach a screenshot.

**To Reproduce**
1. Datadog plugin for Jenkins installed - v 1.0.2
2. Configured valid API token for the datadog plugin
3. Clicked into the 'manage Old Data' screen in Jenkins
4. Reviewed the findings and as per above

**Expected behavior**
There shouldn't be any datadog errors under 'Manage old Data' for pipelines which do not use the plugin.

**Screenshots**
![datadog-plugin-errors](https://user-images.githubusercontent.com/29855998/75755639-e9bf7300-5d26-11ea-9c43-736325ab3b61.png)

**Environment and Versions (please complete the following information):**
Jenkins LTS, v2.204.3
Datadog plugin for Jenkins, v1.0.2

**Comment by gzussa** [comment]
Hi, 

Thanks for opening this issue.

We released a major version (1.0.0) that introduced some backward incompatible changes due to configuration changes. See https://github.com/jenkinsci/datadog-plugin/blob/master/CHANGELOG.md#100--01-07-2020. This `emitOnCheckout` field got renamed into `emitSCMEvents`.

See [README](https://github.com/jenkinsci/datadog-plugin#job-customization) and https://github.com/jenkinsci/datadog-plugin/blob/master/src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogJobProperty/config.jelly#L19.

I hope it helps clarify this. Also note that we are looking to add better support for pipelines in general. If you are interested to provide feedback, we would like to hear from your experience. Feel free to open issues with detailed feedback :) (you can mention this comment as reference)
